### ISSUE TITLE
Panic if /var/spool/cron is not user writable (tempfile creation)

### ISSUE THREAD

**Issue by naufraghi** [systemd-cron/systemd-cron-next#30]
```bash
$ crontab -e
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 13, message: "Permission denied" } }', src/libcore/result.rs:741
```

Perhaps my config was not ok, but I think the `unwrap()` in [crontab.rs#L167](https://github.com/systemd-cron/systemd-cron-next/blob/master/src/bin/crontab.rs#L167)

```
let mut tmpfile = NamedTempFile::new_in(USERS_CRONTAB_DIR).unwrap();
```

should be protected.

I can provide a patch, both in the code and in the docs if someone knows a correct `/var/spool/cron` setup to suggest.

UPDATE: very like [systemd-cron/issues/44](https://github.com/systemd-cron/systemd-cron/issues/44)

**Comment by kstep** [comment]
In a nutshell, yes, that's the case. Either crontab must be suid-root, or sgid with an owning group equal to group of /var/spool/cron (with the last having g+w permissions).

The current setup tries to install crontab as an sgid with a group either crontab (if available) or root. So please check your /var/spool/cron is group writable.

We can make this permissions setup configurable.

As for panic handling, maybe you are right. I left a panic there because it's really exceptional situation, which can happen only if system setup is incorrect.
